# Generated by Django 5.2.9 on 2026-03-15 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0002_alter_billitem_vendor_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billitem',
            name='vendor_product',
        ),
    ]
