# Generated by Django 5.2.9 on 2026-03-15 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0004_billitem_product'),
        ('product', '0014_vendorproducts_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='product.products'),
        ),
    ]
