# Generated by Django 5.2.9 on 2026-03-15 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0005_alter_bank_vendor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendors',
            name='address',
        ),
        migrations.RemoveField(
            model_name='vendors',
            name='city',
        ),
        migrations.RemoveField(
            model_name='vendors',
            name='email',
        ),
        migrations.RemoveField(
            model_name='vendors',
            name='gst_number',
        ),
        migrations.RemoveField(
            model_name='vendors',
            name='pincode',
        ),
        migrations.RemoveField(
            model_name='vendors',
            name='state',
        ),
        migrations.DeleteModel(
            name='Bank',
        ),
    ]
