# Generated by Django 5.2.9 on 2025-12-21 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_products_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='product_code',
            field=models.CharField(default='TEMP_CODE', max_length=100),
        ),
    ]
