# Generated by Django 5.2.9 on 2025-12-21 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_alter_products_product_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='product_code',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
