# Generated by Django 5.2.9 on 2025-12-30 07:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_alter_products_image'),
        ('vendors', '0005_alter_bank_vendor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorproducts',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_products', to='vendors.vendors'),
        ),
    ]
