# Generated by Django 5.2.9 on 2026-03-15 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_alter_vendorproducts_vendor'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='products',
            name='unique_product_per_category',
        ),
        migrations.RemoveConstraint(
            model_name='vendorproducts',
            name='unique_vendor_code',
        ),
        migrations.RemoveField(
            model_name='products',
            name='category',
        ),
        migrations.RemoveField(
            model_name='products',
            name='description',
        ),
        migrations.RemoveField(
            model_name='products',
            name='image',
        ),
        migrations.RemoveField(
            model_name='vendorproducts',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='vendorproducts',
            name='price',
        ),
        migrations.RemoveField(
            model_name='vendorproducts',
            name='stock',
        ),
        migrations.RemoveField(
            model_name='vendorproducts',
            name='vendor_code',
        ),
        migrations.AddField(
            model_name='products',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='products',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='products',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
