# Generated by Django 5.2.9 on 2026-03-15 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_remove_products_unique_product_per_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorproducts',
            name='stock_supplied',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
