# Generated by Django 5.2.9 on 2026-03-15 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_vendorproducts_stock_supplied'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorproducts',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
