# Generated by Django 5.2.9 on 2025-12-30 07:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bill', '0001_initial'),
        ('product', '0011_alter_vendorproducts_vendor'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_qty', models.PositiveIntegerField()),
                ('return_type', models.SmallIntegerField(choices=[(1, 'Sold'), (2, 'Not Sold')])),
                ('customer_name', models.CharField(blank=True, max_length=255, null=True)),
                ('return_reference', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('resolution_type', models.SmallIntegerField(blank=True, choices=[(1, 'Refund'), (2, 'Replacement')], null=True)),
                ('status', models.SmallIntegerField(choices=[(1, 'Pending'), (2, 'Resolved'), (3, 'Rejected')], default=1)),
                ('reason', models.TextField(blank=True, null=True)),
                ('return_date', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_returns', to='bill.bill')),
                ('bill_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_returns', to='bill.billitem')),
                ('vendor_product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_returns', to='product.vendorproducts')),
            ],
            options={
                'db_table': 'product_returns',
            },
        ),
    ]
