# Generated by Django 5.2.9 on 2026-04-28 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0002_transactionitem_service_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transactionitem',
            old_name='service_name',
            new_name='item_name',
        ),
    ]
